### PR TITLE
Kk styling

### PR DESCRIPTION
**Pull request by kjk1325**
# Description

Added styling to article cards to meet acceptance criteria; added Read More button to take user to full article

Closes # (issue)

## Type of change

- [ ] Bug fix
- [X ] New feature
- [ ] Breaking change
- [ ] This change requires a documentation update

## Testing

- run a json-server

```
git fetch kk-styling
npm start
```

- [ ] Article cards should by styled to meet acceptance criteria
- [ ] Read More button should open full article in new window
- [ ] Test C

### CODE REVIEW

**Review by Daniel-L-Ross — CHANGES_REQUESTED** [review]
Kaitlin, it looks like there is a cascading issue to other pages b/c of the use of semantic tags instead of classes. 

@ NewsArticleCard.css lines:
- 1
- 20
- 32

Additionally I use the .friend class for a section on the friendList page. Would using .friend__content make sense on your page?

**Review by SubtleCo — COMMENTED** [review]
Agreed w/ Dan, looks like these changes trickled into other pages. Wild!

**Review by SLLittrell — APPROVED** [review]
Did all the things you intended it to do! good job on the styling!!!

**Review by Daniel-L-Ross — APPROVED** [review]
Article cards look great!!

**Pull request merged**
